# Generated by Django 5.2.7 on 2025-11-29 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vagas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Plano',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_chave', models.CharField(choices=[('basico', 'Básico (Grátis)'), ('intermediario', 'Intermediário'), ('premium', 'Premium')], max_length=20, unique=True)),
                ('nome_exibicao', models.CharField(max_length=100)),
                ('preco', models.DecimalField(decimal_places=2, default=0.0, max_digits=6)),
                ('limite_vagas', models.IntegerField(default=1)),
                ('descricao_curta', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'verbose_name': 'Plano de Assinatura',
                'verbose_name_plural': 'Planos de Assinatura',
            },
        ),
    ]