# Generated by Django 5.2.7 on 2025-12-01 23:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vagas', '0002_plano'),
    ]

    operations = [
        migrations.AddField(
            model_name='vaga',
            name='area_atuacao',
            field=models.CharField(choices=[('tecnologia', 'Tecnologia e Programação'), ('design', 'Design e UX/UI'), ('marketing', 'Marketing e Vendas'), ('financeiro', 'Financeiro e Contabilidade'), ('rh', 'Recursos Humanos'), ('engenharia', 'Engenharia'), ('saude', 'Saúde'), ('educacao', 'Educação'), ('operacional', 'Operacional e Logística'), ('outros', 'Outros')], default='outros', max_length=50, verbose_name='Área de Atuação'),
        ),
    ]
