# Generated by Django 5.2.7 on 2025-11-07 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidato',
            name='curriculo_pdf',
            field=models.FileField(blank=True, null=True, upload_to='curriculos_pdf/'),
        ),
    ]
