# Generated by Django 5.2.7 on 2025-11-17 23:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_candidato_curriculo_pdf'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidato',
            name='bairro',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='candidato',
            name='genero',
            field=models.CharField(blank=True, choices=[('M', 'Masculino'), ('F', 'Feminino'), ('O', 'Outro'), ('P', 'Prefiro não informar')], max_length=1, null=True),
        ),
    ]
