# Generated by Django 5.2.7 on 2025-11-26 22:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0003_candidato_bairro_candidato_genero'),
        ('vagas', '0002_plano'),
    ]

    operations = [
        migrations.AddField(
            model_name='empresa',
            name='plano',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='vagas.plano'),
        ),
    ]
