# Generated by Django 5.2.7 on 2025-11-26 21:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0003_candidato_bairro_candidato_genero'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecuperacaoSenha',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=6)),
                ('metodo', models.CharField(choices=[('email', 'E-mail'), ('sms', 'SMS')], max_length=5)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('expira_em', models.DateTimeField()),
                ('usado', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'recuperacao_senha',
                'ordering': ['-criado_em'],
            },
        ),
    ]
