# Generated by Django 5.2.7 on 2025-11-27 00:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0004_empresa_plano'),
        ('vagas', '0002_plano'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='empresa',
            name='plano',
        ),
        migrations.AddField(
            model_name='empresa',
            name='plano_assinado',
            field=models.CharField(choices=[('basico', 'Plano Básico'), ('intermediario', 'Plano Intermediário'), ('premium', 'Plano Premium')], default='basico', max_length=20, verbose_name='Plano Assinado (Regra de Negócio)'),
        ),
        migrations.AddField(
            model_name='empresa',
            name='plano_fk',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='vagas.plano', verbose_name='Plano (Chave Estrangeira)'),
        ),
    ]
