# Generated by Django 5.2.7 on 2025-11-27 22:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0004_avaliacaoempresa'),
        ('usuarios', '0004_recuperacaosenha'),
    ]

    operations = [
    ]
