# Generated by Django 5.2.7 on 2025-12-01 19:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0005_merge_0004_avaliacaoempresa_0004_recuperacaosenha'),
        ('vagas', '0002_plano'),
    ]

    operations = [
        migrations.AddField(
            model_name='empresa',
            name='plano_assinado',
            field=models.CharField(choices=[('basico', 'Plano Básico'), ('intermediario', 'Plano Intermediário'), ('premium', 'Plano Premium')], default='basico', max_length=20, verbose_name='Plano Assinado (Regra de Negócio)'),
        ),
        migrations.AddField(
            model_name='empresa',
            name='plano_fk',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='vagas.plano', verbose_name='Plano (Chave Estrangeira)'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='email',
            field=models.EmailField(max_length=254, unique=True, verbose_name='email address'),
        ),
    ]
