# Generated by Django 5.2.7 on 2025-12-01 17:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0005_remove_empresa_plano_empresa_plano_assinado_and_more'),
        ('usuarios', '0006_alter_usuario_email'),
        ('usuarios', '0006_empresa_plano_assinado_empresa_plano_fk_and_more'),
    ]

    operations = [
    ]
